### ISSUE TITLE
Agora Miniapp SDK for WeChat 报客户端初始化失败

### ISSUE THREAD

**Issue by HandsomeBoy01** [AgoraIO/Agora-Miniapp-Tutorial#11]
小程序真机调试没问题，但是扫二维码 就不行了，不知道为什么？ 就是下载的Demo 就修改了一下Appid 没有开启证书，测试环境，怀疑SDK 有问题了

**Comment by plutoless** [comment]
没太懂，真机调试就是扫二维码调的吧

**Comment by plutoless** [comment]
你说的二维码是什么？能提供一下错误日志吗

**Comment by mengxin-FE** [comment]
我也是运行提示客户端初始化失败，这么久了没人管吗

**Comment by plutoless** [comment]
@mengxin-FE 请问有详细日志吗？我们这边都有客户在用的，没有问题的哈

**Comment by mengxin-FE** [comment]
> @mengxin-FE 请问有详细日志吗？我们这边都有客户在用的，没有问题的哈

按照SDK文档来做的，目前是这个结果
![image](https://user-images.githubusercontent.com/14139852/110886907-569b1f00-8324-11eb-9d95-d3f2edcd651b.png)

![image](https://user-images.githubusercontent.com/14139852/110886879-4d11b700-8324-11eb-859f-ecf1e4f3302a.png)

**Comment by plutoless** [comment]
@mengxin-FE 这边可以看下控制台是否有打开token，如果有打开需要在加入的时候传一下token，控制台应该可以生成临时token
