### ISSUE TITLE
没有声音 也看不到对方

### ISSUE THREAD

**Issue by meiqi1992** [AgoraIO/Agora-Miniapp-Tutorial#15]
使用demo 说明 更换了appid 和token 加入频道成功了，但是看不到对方，也听不到任何声音，是为什么

**Comment by plutoless** [comment]
这边能提供一下日志吗?

**Comment by meiqi1992** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/15257730/119428238-1d792500-bd3f-11eb-8eaf-d4938fead942.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/15257730/119428382-57e2c200-bd3f-11eb-9911-1ebd0f35c64d.png">

我在小程序上上传了日志

**Comment by plutoless** [comment]
能提供一下完整的日志吗? 看起来推流应该成功了，但拉流部分看不到

**Comment by meiqi1992** [comment]
是账号的问题，我换了个账号，就成功了
