### ISSUE TITLE
stream-removed 回调函数拿到的uid是个数组

### ISSUE THREAD

**Issue by soulcm** [AgoraIO/Agora-Miniapp-Tutorial#21]
rtc监听 stream-removed事件，回调函数中uid按[文档](https://docs.agora.io/cn/Voice/API%20Reference/wechat/interfaces/client.html#on)不是个number吗，但实际拿到的是个数组类型

**Comment by plutoless** [comment]
@soulcm 应该是个事件对象，在对象中有uid属性

**Comment by soulcm** [comment]
> @soulcm 应该是个事件对象，在对象中有uid属性

![image](https://user-images.githubusercontent.com/5706155/133870809-59bbd099-ab23-4d56-afaa-9eb011e9780a.png)

嗯，是这个文档吧，但我这边取出来的uid是一个 `number[]`数组类型
