### ISSUE TITLE
小程序SDK是否能提供npm包呢

### ISSUE THREAD

**Issue by wong2** [AgoraIO/Agora-Miniapp-Tutorial#23]

**Comment by QinZhen001** [comment]
hello 最新版本sdk 已提供 npm包
集成文档：https://docs.agora.io/cn/live-streaming-premium-4.x/start_call_wechat#%E9%80%9A%E8%BF%87-npm-%E9%9B%86%E6%88%90
npm地址：https://www.npmjs.com/package/agora-miniapp-sdk
