### ISSUE TITLE
请问 Agora小程序SDK，是否支持 百度/字节/快手 小程序？

### ISSUE THREAD

**Issue by jinmingpang** [AgoraIO/Agora-Miniapp-Tutorial#24]
除了微信/QQ 小程序外，是否支持其他平台小程序呢？比如 百度/字节/快手 。

**Comment by plutoless** [comment]
@CareyToboo 您好，这主要依托于这些平台是否提供了类似微信小程序 liveplayer/livepusher的组件，目前从已知情况看，这些小程序并没有提供实时推流/拉流的组件，这种情况下是不支持的
