### ISSUE TITLE
小程序推流失败

### ISSUE THREAD

**Issue by 404NotFoundY** [AgoraIO/Agora-Miniapp-Tutorial#26]
小程序最新版本，应该是兼容问题，一部分手机是正常的，但是客户反馈推流失败

![img_v2_06f79635-7dd6-4ce8-b650-b578ca957a9g](https://user-images.githubusercontent.com/50349075/234521897-7e7824cc-c159-47d2-8c3b-930052815df3.png)

**Comment by QinZhen001** [comment]
你好 可以提供一下手机机型，微信版本之类的信息嘛？ 或者提供一下log日志
