### ISSUE TITLE
v2.4.0，当改变布局的时候在安卓端发起的视频在其他player端显示黑屏

### ISSUE THREAD

**Issue by PrintingChen** [AgoraIO/Agora-Miniapp-Tutorial#6]
当我点击视频切换视图时（大屏变小屏，小屏变大屏），这个时候在其他player看到pusher端的画面就是黑屏，布局使用的是layout.js的这个文件来计算的

**Comment by plutoless** [comment]
本地预览正常吗？话说大屏切小屏不work吧，小程序没法改z-order

**Comment by PrintingChen** [comment]
> 本地预览正常吗？话说大屏切小屏不work吧，小程序没法改z-order

本地预览是正常，如果通过layout.js一次计算完成后，如果后面再改动media数组里面某个流的参数，比如改变其x,y,width,height,就会出现黑屏的问题的，您有啥解决方案吗

**Comment by plutoless** [comment]
pusher的status code是啥？按道理只是改变宽高应该不会重置live-pusher的，除非你改了media数组里对象的id

**Comment by plutoless** [comment]
你也可以开一下live-pusher的debug

**Comment by PrintingChen** [comment]
> pusher的status code是啥？按道理只是改变宽高应该不会重置live-pusher的，除非你改了media数组里对象的id

除了x,y,width,height这个四个参数，其他的都没有改变的，live-pusher就是没有推流了的，好奇怪啊^_^
方法提供下您的微信交流下吗？或者您方便也可以加下我？我的wx：cyt18877829325

**Comment by plutoless** [comment]
把Live-pusher设成debug模式，然后改参数后不推流的状态下截个图我给看看
