### ISSUE TITLE
meeting切换到其他页面时，再返回meeting时发现用用户订阅不到

### ISSUE THREAD

**Issue by PrintingChen** [AgoraIO/Agora-Miniapp-Tutorial#7]
使用官方demo时，如果从meeting页面使用wx.reLaunch跳转到其他页面后，然后在跳转到meeting页面时发现有用户没订阅到（页面跳转过程中房间里面的用户谁都没有退出），比如原来房间5个人，切换回来时可能只有3个或四个人了，这是什么问题

**Comment by plutoless** [comment]
看下日志？用户回来后有做重新join吗？重新join有收到所有用户的stream-added吗？

**Comment by PrintingChen** [comment]
> 

> 看下日志？用户回来后有做重新join吗？重新join有收到所有用户的stream-added吗？

有的呢，都是按照官方的demo来的，返回来就和一开始进入meeting页面一样初始化了，相当于重新开始

**Comment by plutoless** [comment]
弄个日志给我看下？

**Comment by PrintingChen** [comment]
> 弄个日志给我看下？
可以的啊

**Comment by PrintingChen** [comment]
日志打印的确实是没有回调stream-add的，即使原来房间有人

**Comment by plutoless** [comment]
弄个日志给我看下吧
