### ISSUE TITLE
小程序这个demo运行后，没有任何报错，一直显示加载中，请问是什么原因？

### ISSUE THREAD

**Issue by hiwhitley** [AgoraIO/Agora-Miniapp-Tutorial#8]
小程序这个demo运行后，没有任何报错，一直显示加载中，请问是什么原因？

**Comment by plutoless** [comment]
模拟器？

**Comment by hiwhitley** [comment]
真机和模拟器都是显示加载中，声网appid已经开通过。

**Comment by hiwhitley** [comment]
> 模拟器？
真机和模拟器都是显示加载中，声网appid已经开通过。

**Comment by hiwhitley** [comment]
> 模拟器？

真机和模拟器都是显示加载中，声网appid已经开通过。

**Comment by plutoless** [comment]
本地的也是吗？可以点一下下面功能按钮最右边的日志上传，点一下后可以开启debug模式

**Comment by hiwhitley** [comment]
> 本地的也是吗？可以点一下下面功能按钮最右边的日志上传，点一下后可以开启debug模式

2019/08/09 10:20:44:675: ["Fri Aug 09 2019 10:20:44 GMT+0800 (China Standard Time) [DEBUG]: ","Report succcess: ",{"uri":8003,"miniappSession":null,"miniappJoinChooseServer":null,"miniappConnectWebSocket":null,"miniappJoin":{"header":{"sid":"1329BEEF85CE450B90D9203F240377A3","cname":"7777","cid":null,"lts":1565317244437,"ip":null,"uid":644058,"success":true,"elapse":1925,"peer":null},"uid":null,"isrejoin":false,"details":"{\"seq\":6,\"appId\":\"e139bdbf217b4b0cb34dc4007969f9b3\",\"wsurl\":\"wss://miniapp.agoraio.cn/120-92-141-119/api\"}"},"miniappPublish":null,"miniappUnpublish":null,"miniappSubscribe":null,"miniappUnsubscribe":null,"miniappLeave":null,"miniappServerEvent":null,"miniappPusherState":null,"miniappPlayerState":null}]
util.js:59 2019/08/09 10:20:44:677: client publish success
util.js:59 2019/08/09 10:20:44:975: ["Fri Aug 09 2019 10:20:44 GMT+0800 (China Standard Time) [DEBUG]: ","Report succcess: ",{"uri":8004,"miniappSession":null,"miniappJoinChooseServer":null,"miniappConnectWebSocket":null,"miniappJoin":null,"miniappPublish":{"header":{"sid":"1329BEEF85CE450B90D9203F240377A3","cname":"7777","cid":null,"lts":1565317244671,"ip":null,"uid":644058,"success":true,"elapse":2159,"peer":null},"pushurl":"rtmp://120.92.141.119:7221/live/qM82z3nQ2B6ScAahRkaMSJNcTCz3ObHy","uid":null,"details":"{\"seq\":7}"},"miniappUnpublish":null,"miniappSubscribe":null,"miniappUnsubscribe":null,"miniappLeave":null,"miniappServerEvent":null,"miniappPusherState":null,"miniappPlayerState":null}]

本地也是一样，一直加载中，日志显示 client publish success，请问是啥原因？

**Comment by plutoless** [comment]
publish success只是成功拿到了推流地址，你还需要把推流地址设置到live-pusher里
如果本地也不行，1. 检查地址是否设置正确 2. 检查摄像头麦克风权限是否给了

**Comment by LLLLLZQ** [comment]
你好，我这边也显示这个 一直加载中，这个是什么问题导致的

**Comment by plutoless** [comment]
@LLLLLZQ 有日志吗？可以提供下日志

**Comment by wangz-code** [comment]
我这边测试也是一直加载中, SDK使用的是 Agora_Miniapp_SDK_for_WeChat_v2.5.3.zip
是因为没有实名认证吗?
