### ISSUE TITLE
官网上的新SDK似乎已经不兼容了，Agora Miniapp SDK for WeChat 报客户端初始化失败

### ISSUE THREAD

**Issue by luxuze** [AgoraIO/Agora-Miniapp-Tutorial#9]

**Comment by plutoless** [comment]
@luxuze 我们应该没改过接口，检查一下appid是否正确，如果dashboard打开了证书，加入频道时是否带了token

**Comment by plutoless** [comment]
@luxuze 我们应该没改过接口，检查一下appid是否正确，如果dashboard打开了证书，加入频道时是否带了token

**Comment by plutoless** [comment]
@luxuze 你也可以问下斯橙。。

**Comment by luxuze** [comment]
应该不是appid的问题，官网上sdk文件的名字已经和代码里面的不一样了，应该是sdk版本不兼容导致的。

**Comment by cuiyajie** [comment]
@plutoless ,我看了一下，官网的SDK没有地方填写token

**Comment by plutoless** [comment]
@cuiyajie 需要在meeting页面文件的join方法里填写，第一个参数就是

**Comment by plutoless** [comment]
@luxuze 如果是文件名字的问题，需要自己修改一下文件名哈
